"""Train ICI propensity score models on pre-generated embedding datasets.

Trains two propensity models per cohort:
  1. Covariates-only: LR on demographics + cancer type (+ line dummies for cohort 2)
  2. Covariates + embeddings: LR on covariates + text embeddings

Note: panel version is not included in the PS model (it is included as a confounder
in the downstream Cox models). This is intentional — panel version may act as a
mediator of ICI assignment and is not purely a pre-treatment confounder.

Uses 5-fold stratified CV to produce held-out propensity scores.

Expects embedding datasets generated by ICI_generate_embeddings.py.
"""

import os
import warnings
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.exceptions import ConvergenceWarning
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import roc_auc_score, roc_curve

warnings.filterwarnings('ignore', category=ConvergenceWarning)

from biomarker_common import DATA_PATH, SURV_PATH

# ============================================================
# Configuration
# ============================================================
COHORTS = ['cohort1', 'cohort2']
BUFFERS = [30]
PS_MODELS = ['covariates_only', 'covariates_plus_embeddings']

cancer_type_df = pd.read_csv(
    os.path.join(DATA_PATH, 'clinical_and_genomic_features/cancer_type_df.csv.gz'))


# === Propensity CV training function ===
def train_propensity_cv(pred_df, feature_cols, label):
    """Train elastic-net logistic regression with nested CV for hyperparameter
    tuning and held-out propensity scores.

    Outer loop: 5-fold stratified CV produces held-out predictions.
    Inner loop: LogisticRegressionCV tunes C and l1_ratio via 3-fold CV
                within each outer training fold.
    """
    X = pred_df[['DFCI_MRN'] + feature_cols].copy()
    y = pred_df['PX_on_ICI'].astype(int)

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1234)

    cv_mrns, cv_preds, cv_probs, cv_true = [], [], [], []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y), 1):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        cv_mrns += X_test['DFCI_MRN'].tolist()
        X_train = X_train.drop(columns=['DFCI_MRN'])
        X_test = X_test.drop(columns=['DFCI_MRN'])

        scaler = StandardScaler().fit(X_train)
        X_train_s = scaler.transform(X_train)
        X_test_s = scaler.transform(X_test)

        clf = LogisticRegressionCV(
            penalty='elasticnet',
            solver='saga',
            Cs=8,
            l1_ratios=[0.1, 0.5, 0.9],
            cv=3,
            scoring='roc_auc',
            max_iter=2000,
            tol=1e-3,
            random_state=1234,
            n_jobs=4,
        )
        clf.fit(X_train_s, y_train.values.ravel())

        n_nonzero = np.sum(clf.coef_ != 0)
        n_total = clf.coef_.size
        print(f"    fold {fold}: C={clf.C_[0]:.4f}, l1_ratio={clf.l1_ratio_[0]:.2f}, "
              f"features={n_nonzero}/{n_total}")

        cv_preds += clf.predict(X_test_s).tolist()
        cv_probs += clf.predict_proba(X_test_s)[:, 1].tolist()
        cv_true += y_test.tolist()

    auc = roc_auc_score(cv_true, cv_probs)
    print(f"  [{label}] AUC = {auc:.4f}")

    return pd.DataFrame({
        'DFCI_MRN': cv_mrns,
        'model_preds': cv_preds,
        'model_probs': cv_probs,
        'ground_truth': cv_true,
    })


# ============================================================
# Main loop
# ============================================================
for COHORT in COHORTS:
    print(f"\n{'='*60}")
    print(f"[ICI_train_propensity] Cohort: {COHORT}")
    print(f"{'='*60}")

    OUTPUT_BASE = os.path.join(DATA_PATH, f'treatment_prediction/{COHORT}/')
    EMBEDDING_DATA_PATH = os.path.join(OUTPUT_BASE, 'prediction_data/')

    for buffer in tqdm(BUFFERS, desc="Training propensity models"):
        buffer_input_path = os.path.join(EMBEDDING_DATA_PATH, f'w_{buffer}_day_buffer/')

        pred_df = pd.read_csv(
            os.path.join(buffer_input_path, f'ICI_prediction_df_w_{buffer}_day_buffer.csv.gz'))

        # Embedding feature columns
        embedding_cols = [col for col in pred_df.columns
                          if ('IMAGING' in col) or ('PATHOLOGY' in col) or ('CLINICIAN' in col)]

        # Build covariate feature set
        pred_with_covars = pred_df.merge(cancer_type_df, on='DFCI_MRN', how='left')

        cancer_type_feature_cols = [c for c in pred_with_covars.columns if c.startswith('CANCER_TYPE_')]
        # Line category dummies: cohort 1 is first-line ICI only — no line variation to adjust for
        if COHORT != 'cohort1':
            pred_with_covars['line_category'] = pred_with_covars['line_category'].clip(upper=3)
            pred_with_covars = pd.get_dummies(
                pred_with_covars, columns=['line_category'], prefix='LINE', drop_first=True, dtype=int)
            line_feature_cols = [c for c in pred_with_covars.columns if c.startswith('LINE_')]
        else:
            line_feature_cols = []

        demo_cols = ['GENDER', 'AGE_AT_TREATMENTSTART']
        if 'GENDER' not in pred_with_covars.columns or 'AGE_AT_TREATMENTSTART' not in pred_with_covars.columns:
            surv_demo = pd.read_csv(os.path.join(SURV_PATH, 'death_met_surv_df.csv.gz'),
                                    usecols=['DFCI_MRN', 'GENDER', 'AGE_AT_TREATMENTSTART'])
            pred_with_covars = pred_with_covars.merge(surv_demo, on='DFCI_MRN', how='left')

        covar_cols = (demo_cols + cancer_type_feature_cols + line_feature_cols)
        covar_cols = [c for c in covar_cols if pred_with_covars[c].notna().any()]

        covar_plus_embed_cols = covar_cols + embedding_cols
        covar_plus_embed_cols = [c for c in covar_plus_embed_cols if pred_with_covars[c].notna().any()]

        # Use the same patients for both PS models: restrict to those with
        # complete data for the most demanding feature set (covariates + embeddings).
        common_source_df = pred_with_covars.dropna(subset=covar_plus_embed_cols)
        print(f"    Common patient set: {len(common_source_df)} "
              f"(dropped {len(pred_with_covars) - len(common_source_df)} with missing embeddings/covariates)")

        for ps_model in PS_MODELS:
            output_path = os.path.join(OUTPUT_BASE, f'{ps_model}_propensity/w_{buffer}_day_buffer/')
            os.makedirs(output_path, exist_ok=True)

            if ps_model == 'covariates_only':
                features = covar_cols
            else:
                features = covar_plus_embed_cols

            label = f"buffer={buffer}, {ps_model}"
            out_df = train_propensity_cv(common_source_df, features, label)
            out_df.to_csv(os.path.join(output_path, 'predictions.csv.gz'), index=False)

    # === Plot ROC curves for the 30-day buffer ===
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    PLOT_BUFFER = 30

    for i, ps_model in enumerate(PS_MODELS):
        pred_path = os.path.join(OUTPUT_BASE, f'{ps_model}_propensity/w_{PLOT_BUFFER}_day_buffer/predictions.csv.gz')
        pred_df = pd.read_csv(pred_path)

        auc = roc_auc_score(pred_df['ground_truth'], pred_df['model_probs'])
        fpr, tpr, _ = roc_curve(pred_df['ground_truth'], pred_df['model_probs'])

        ax = axes[i]
        sns.set_style("whitegrid")
        sns.lineplot(x=fpr, y=tpr, ax=ax, label=f'AUC = {auc:.3f}')
        sns.lineplot(x=[0, 1], y=[0, 1], ax=ax, linestyle='--', color='gray')
        ax.set_title(f'{ps_model} ({COHORT}, buffer={PLOT_BUFFER}d)')
        ax.set_xlabel('False Positive Rate')
        ax.set_ylabel('True Positive Rate')
        ax.legend(loc='lower right')

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_BASE, f'propensity_ROC_{COHORT}.png'), dpi=150)
    plt.show()
    print(f"[ICI_train_propensity] Done with {COHORT}. Outputs in {OUTPUT_BASE}")
